main: "me.roinujnosde.titansbattle.TitansBattle"
name: "TitansBattle"
author: "RoinujNosde"
version: ${project.version}
api-version: 1.13
softdepend:
  - "SimpleClans"
  - "Factions"
  - "mcMMO"
  - "PlaceholderAPI"
  - "Essentials"
permissions:
  titansbattle.admin:
    description: "Gives access to administrator commands"
    default: op
    children:
      titansbattle.player: true
      titansbattle.reload: true
      titansbattle.cancel: true
      titansbattle.start: true
      titansbattle.setdestination: true
      titansbattle.setinventory: true
  titansbattle.player:
    description: "Gives access to player commands"
    default: false
    children:
      titansbattle.join: true
      titansbattle.exit: true
      titansbattle.watchroom: true
      titansbattle.help: true
      titansbattle.winners: true
      titansbattle.ranking: true
  titansbattle.join:
    default: false
  titansbattle.exit:
    default: false
  titansbattle.watchroom:
    default: false
  titansbattle.help:
    default: false
  titansbattle.reload:
    default: false
  titansbattle.cancel:
    default: false
  titansbattle.start:
    default: false
  titansbattle.setdestination:
    default: false
  titansbattle.winners:
    default: false
  titansbattle.setinventory:
    default: false
  titansbattle.ranking:
    default: false
